name: Publish Install Scripts

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Compile .NET Core init DLL
      run: ./build.sh
      working-directory: scripts/netcore
      
    - uses: actions/setup-java@v1
      with:
        java-version: '10'
    - name: Compile Java init JAR
      run: ./build.sh
      working-directory: scripts/java
      
    - uses: chrislennon/action-aws-cli@v1.1
    - name: Deploy to S3
      run: aws s3 sync --delete --exclude="$PWD/*/*" ./ s3://lets.tunshell.com/ --acl=public-read --cache-control max-age=7200 --metadata-directive REPLACE 
      working-directory: scripts
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACT_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACT_AWS_SECRET_ACCESS_KEY }}
        
    - name: Invalidate CloudFront
      run: aws cloudfront create-invalidation --distribution-id=EN7FC8CHF6D8E --paths '/*'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACT_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACT_AWS_SECRET_ACCESS_KEY }}