name: Publish Client Docker

on:
  push:
    branches:
      - master

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: timetoogo/tunshell
        dockerfile: tunshell-client/docker/prod.Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"