name: Publish Server Docker

on:
  push:
    branches:
      - master
      - enhancement/rust

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: timetoogo/tunshell-relay
        dockerfile: tunshell-server/docker/prod.Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"