name: Publish Server Docker

on:
  push:
    branches:
      - master
      - enhancement/rust

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Build Docker Image
      run: ls -al && docker build -t timetoogo/tunshell-relay --file=tunshell-server/docker/prod.Dockerfile .
    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: timetoogo/tunshell-relay
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest"