name: Publish Client Libraries

on:
  push:
    branches:
      - master
      - enhancement/rust

jobs:
  build_and_deploy:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
      shell: bash
      working-directory: build
    - run: ./install-deps.sh
      working-directory: build
      shell: bash
      env:
        TEMPDIR: /tmp
    - run: ./cross-compile.sh "targets.$(echo "${{ matrix.platform }}" | cut -d'-' -f1).json"
      working-directory: build
      shell: bash
      env:
        TEMPDIR: /tmp
    # Deploy artifact to https://artifacts.debugmypipeline.com
    - uses: chrislennon/action-aws-cli@v1.1
    - name: Deploy to S3
      run: aws s3 cp --recursive artifacts/ s3://artifacts.debugmypipeline.com/ --acl=public-read --cache-control max-age=31536000 --metadata-directive REPLACE
      working-directory: build
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACT_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACT_AWS_SECRET_ACCESS_KEY }}
    - name: Invalidate CloudFront
      run: aws cloudfront create-invalidation --distribution-id=E3UKYOV4DA9TM1 --paths '/*'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACT_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACT_AWS_SECRET_ACCESS_KEY }}