name: Run Integration Tests

on:
  push:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: ./test.sh
      working-directory: tunshell-tests
      shell: bash
      env:
        RUST_TEST_THREADS: 1

