name: Testing

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: curl -sSf https://lets.tunshell.com/initbeta.sh | sh -s -- T gpp7NW0XNHI3sdy1ynp6Zy kQQ8uC35J2LQGMozHaiASR au.relay.tunshell.com
     
