name: Testing

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T tvlPGaO1ieXwwBXfApJjQz g1xl8YUb094iwQcRGr7o73 au.relay.tunshell.com
     
