name: Feasibility test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: chmod +x scripts/pipeline.sh
    - run: scripts/pipeline.sh